######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 29 17:22:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_helloworld.cpp
